### ISSUE TITLE
Settings icon is the default cog icon

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/diagnostics#14]
Going to the settings view, in the left sidebar we can see:

![screen shot 2017-08-03 at 14 33 52](https://user-images.githubusercontent.com/9048796/28922063-fae69c36-7858-11e7-853a-ed05b98b7c69.png)

It should be the same or similar to the icon in the apps view:

![screen shot 2017-08-03 at 14 36 05](https://user-images.githubusercontent.com/9048796/28922102-244cb042-7859-11e7-9802-7bd087751f38.png)

cc @felixheidecke

**Comment by DeepDiver1975** [comment]
@mrow4a it should be possible to simply reuse this icon - right? THX

**Comment by mrow4a** [comment]
@DeepDiver1975 I have no idea how the frontend icon stuff works, just used something which will not take me too much time.

**Comment by tomneedham** [comment]
at the moment in core you can only use the default ones - need enhancement to settings/sections stuff to allow you to use custom icons

**Comment by DeepDiver1975** [comment]
> I have no idea how the frontend icon stuff works,

try to get that understanding ;-)

ths icon itself is fine for me - where did you get it from? license? @pmaier1 agree?

**Comment by DeepDiver1975** [comment]
> need enhancement to settings/sections stuff to allow you to use custom icons

ouch

**Comment by pmaier1** [comment]
> ths icon itself is fine for me - where did you get it from? license? @pmaier1 agree?

If no issues regarding licenses, fine for me as well.

> at the moment in core you can only use the default ones  - need enhancement to settings/sections stuff to allow you to use  custom icons

This applies to all apps in general? If this is the case we need this enhancement soon as it doesn't look nice when we use the same icon several times. Is there a ticket?

**Comment by tomneedham** [comment]
> Is there a ticket?

not yet

**Comment by DeepDiver1975** [comment]
> not yet

who will open one?

**Comment by pmaier1** [comment]
> who will open one?

I would but I don't know what is needed to be done. What about https://github.com/owncloud/core/pull/28580? Is this related or is it just extending defaults/workaround?

**Comment by pmaier1** [comment]
Increasing priority. As I assume that this app won't get many releases in the near future I would like to have a proper icon here. @felixheidecke maybe?

**Comment by mrow4a** [comment]
@pmaier1 @felixheidecke do we have anything new here?

**Comment by felixheidecke** [comment]
I inverted the icon to be used in the setting panel. Just tell me where to put it and I'll put it there.

**Comment by tomneedham** [comment]
@pmaier1 requires https://github.com/owncloud/core/issues/28751 ideally.

@felixheidecke or, place the icon in diagnostics and add the necessary styling. Change https://github.com/owncloud/diagnostics/blob/master/lib/Panels/Section.php#L40 to some identifier and then use selector:

![screen shot 2017-08-21 at 10 41 16](https://user-images.githubusercontent.com/660805/29513453-519ceb36-865d-11e7-988f-3ae3047db8f3.png)

`.icon-shield` is just: `background-image: url('../img/apps/shield.svg')` but instead use the path from diagnostics

**Comment by pmaier1** [comment]
> @pmaier1 requires owncloud/core#28751 ideally.

Thanks @tomneedham. Probably this won't make it to 10.0.3 so I moved it to 10.0.4. Let's for now use the 'workaround' and go the nice way from 10.0.4 on. @felixheidecke you know all you need to know?

**Comment by felixheidecke** [comment]
> you know all you need to know?

Hopefully ;-)

**Comment by felixheidecke** [comment]
> place the icon in diagnostics and add the necessary styling

@tomneedham @pmaier1 … I can't apply styling using css from the diagnostics app since the `settings-admin.css` isn't loaded in the general settings section. :disappointed:

**Comment by pmaier1** [comment]
> @tomneedham @pmaier1 … I can't apply styling using css from the diagnostics app since the settings-admin.css isn't loaded in the general settings section. (…/settings/personal) :disappointed:

How can we solve this? @mrow4a @tomneedham

**Comment by felixboehm** [comment]
@felixheidecke please care for this one, talk with @PVince81 if you need help.

**Comment by mrow4a** [comment]
Any new input here?

**Comment by tomneedham** [comment]
Pushing a PR now
