### ISSUE TITLE
In the users dropdown, LDAP users are shown using uuid instead of displayname after a refresh.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/diagnostics#20]
### Steps to reproduce

1. Set up an ldap server.
2. Login with one of the ldap users 'ldap_user'.
3. Go to the diagnostics settings.
4. Choose ldap user 'ldap user' in the dropdown.
5. Refresh the page.

### Expected behaviour
Metadata is still there after files are renamed and moved.

### Actual behaviour
You choose 'ldap user' in the dropdown, but after refreshing the page the uuid is shown.

![ldap_user_diagnostics_app](https://user-images.githubusercontent.com/9048796/29410261-17593688-8350-11e7-9e08-11bb2e4a3a85.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**Browser**
Chrome, Safari

cc @mrow4a

**Comment by SergioBertolinSG** [comment]
Same problem in the logs:
```json
{"type":"SUMMARY","reqId":"nehEppnrcBqOytIwFTHQ","time":"2017-08-17T11:44:06+00:00","remoteAddr":"HIDDEN_IP","user":"b8df1298-8742-1034-8cb4-39af73a96b9a","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","diagnostics":{"totalSQLQueries":10,"totalSQLDurationmsec":3.7293434143066,"totalSQLParams":11,"totalEvents":10,"totalEventsDurationmsec":19.32430267334}}
```

**Comment by tomneedham** [comment]
well, looks like its using userids. IMO, logs should use userids, but maybe the UI can use display names here

**Comment by cdamken** [comment]
@butonic FYI

**Comment by butonic** [comment]
IMO logs must have the accountid and the userid, they should have email and display name as well to make working with logs a little easier.

**Comment by butonic** [comment]
that input field should use the same dialog as the sharing ui with a dropdown for users / groups with avatars and displayname. at the very least show the displayname in the UI after selecting a user.
